src/api/cloudrootfs.md
src/api/clusterfile.md
src/api/kubefile.md
src/docs/advanced/define-cloudimage.md
src/docs/getting-started/build-cloudimage.md
src/docs/reference/kubefile.md
src/index.md
src/zh/advanced/define-cloudimage.md
src/zh/getting-started/applications.md
src/zh/getting-started/build-cloudimage.md
src/zh/index.md
src/zh/reference/kubefile.md

fixed an issue where removing an application module caused markdown linter to detect dead links.
fixed page footer link display problem.
Signed-off-by: wb-hjh933779 <wb-hjh933779@alibaba-inc.com>

fixed an issue where removing an application module caused markdown linter to detect dead links.

---

src/docs/advanced/architecture.md

fix tiny typo

---

src/docs/getting-started/build-appimage.md
src/docs/getting-started/build-cloudimage.md

doc:make build doc more readable

---

src/.vuepress/config.js

fix wrong logo image address.
Signed-off-by: wb-hjh933779 <wb-hjh933779@alibaba-inc.com>

fix wrong logo image address.

---

src/docs/getting-started/using-clusterfile.md

add user case of env render at cluster file

---

src/zh/getting-started/quick-start.md

update the command parameters of the error

docs: update command parameter

---

src/docs/reference/cloudrootfs.md
src/zh/reference/cloudrootfs.md

Signed-off-by: Lan-ce-lot <1984737645@qq.com>
fix tiny typo in cloudrootfs.md

fix typo in cloudrootfs.md

---

src/docs/introduction/architecture.md

Add architecture

---

src/docs/concept/clusterfile.md

add clusterfile

---

src/docs/getting-started/install-sealer.md
src/docs/help/contact.md
src/docs/help/faq.md
src/docs/sealer-images/cluster-images.md

add help
1. contact.md
2. faq.md
add installer sealer doc
add sealer-images
1. cluster-images.md

add sealer v0.9.0 doc

---

src/docs/command/cluster/sealer_run.md
src/docs/command/image/sealer_build.md
src/docs/command/image/sealer_pull.md
src/docs/command/image/sealer_rmi.md
src/docs/command/image/sealer_save.md
src/docs/command/image/sealer_tag.md
src/docs/concept/clusterfile.md
src/docs/concept/kubefile.md

replace example cluster image name to the docker io  address 

---

src/.vuepress/config.js

Signed-off-by: yuxing.lyx <yuxing.lyx@alibaba-inc.com>

chore: comment out some invalid or todo documents

---

.github/workflows/release.yml

 delete scheduled release

---

src/.vuepress/config.js

add nav for zh

---

.github/workflows/manually-publish.yml

 add manually publish official website

---

src/docs/sealer-images/cluster-images.md

Add arm64 image list

---

src/docs/concept/kubefile.md

Signed-off-by: yuxing.lyx <yuxing.lyx@alibaba-inc.com>

chore: update helm chart type app case

---

src/docs/concept/kubefile.md

Signed-off-by: yuxing.lyx <yuxing.lyx@alibaba-inc.com>

chore: add more instructions for kubefile

---

src/docs/command/alpha/sealer_alpha_mount.md
src/docs/command/alpha/sealer_alpha_umount.md

Add mount and umount doc

---

src/docs/getting-started/install-sealer.md
src/docs/sealer-images/cluster-images.md

Add image list

---

src/docs/concept/clusterfile.md

doc: add application

---

src/v0.9.0/sealer-images/cluster-images.md

fix: Image version corresponding error

---

src/docs/concept/clusterfile.md

add plugin executed order

---

src/docs/sealer-images/cluster-images.md

chore: optimize the cluster image reference

---

src/docs/concept/clusterfile.md

doc: add app config for file modification

---

src/docs/command/cluster/sealer_apply.md
src/docs/command/cluster/sealer_delete.md
src/docs/command/cluster/sealer_run.md
src/docs/command/cluster/sealer_scale-up.md
src/docs/command/cluster/sealer_upgrade.md
src/docs/concept/clusterfile.md

add sealer upgrade related docs

add upgrade doc

---

src/.vuepress/config.js
src/docs/advanced/customize-cluster-image.md
src/docs/advanced/run-with-clusterfile.md
src/docs/getting-started/quick-start.md
src/docs/sealer-images/cluster-images.md

After sealer run k0s cluster supported, we need to have a doc which could lead user how to run and build an image for k0s.
NONE

add k0s describe.

---

src/docs/advanced/customize-cluster-image.md

Add best practices

---

src/.vuepress/config.js
src/docs/advanced/sealer-run-rootless.md
src/docs/getting-started/quick-start.md

Signed-off-by: Xinwei Xiong <3293172751nss@gmail.com>
sealer needs to support rootless, this PR will fix it
https://github.com/sealerio/sealer/issues/1999
http://localhost:8080/docs/advanced/sealer-run-rootless.html#prerequisites

docs: sealer is not supported by root users

---

src/docs/advanced/customize-cluster-image.md
src/docs/advanced/run-with-clusterfile.md
src/docs/concept/clusterfile.md

modify `aliyun.com/v1alpha1` to `sealer.io/v1`

---

src/docs/concept/clusterfile.md

add more plugin description

---

.github/workflows/.mlc_config.json
.github/workflows/markdown.yml

feat: change markdown link check tool

---

src/docs/concept/clusterfile.md
src/v0.9.0/concept/clusterfile.md
src/v0.9.1/concept/clusterfile.md
src/v0.9.2/concept/clusterfile.md

bugfix: delete blank for tmpl file render
